# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7db83d1dc9572099f93f3e5c1c7ca356b71134a63851818374396974208b9606a62523df6571e6eec170e4575a4f2899b001ce4f273c3645690e53c2d83f6fcc

test:
  secret_key_base: da71b208619f5ffb8362875e292e3b7f52fa9884d65fdd840ef35fedcfc6bde8e13ead693df09c1c03003a4a646b38b2136c44960fc0369804be20d1515ff397

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
